 database:
    image: ghcr.io/quod-financial/postgres_marketsim:latest
    container_name: market-simulator-database
    networks:
      - market-simulator-net
    ports:
      - 15432:5432
    volumes:
      - "${DB_DATA}"
    environment:
      - POSTGRES_DB=simdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --user=postgres --dbname=simdb" ]
      retries: 2
      interval: 5s
      timeout: 10s

  liquibase:
    image: ghcr.io/quod-financial/liquibase:latest
    container_name: market-simulator-liquibase
    networks:
      - market-simulator-net
    depends_on:
      database:
        condition: service_healthy
