services:
  XETRA:
    image: ghcr.io/quod-financial/deploy_marketsim:latest
    container_name: XETRA
    networks:
      - market-simulator-net
    ports:
      - "9050:9050" # Port to send REST API requests
      - "9051:9051" # Port to send FIX messages
    volumes:
      - ./:/market-simulator/quod/data/
    environment:
      - INSTANCE_ID=XETRA
      - PREFIX=QUOD
    depends_on:
      liquibase:
        condition: service_completed_successfully

  networks:
    market-simulator-net:
      external: true

